# Generated by Django 3.1.1 on 2020-10-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20201003_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='person1',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='person2',
        ),
    ]
