# Generated by Django 3.1.1 on 2020-10-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20201004_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users'),
        ),
    ]
