# Generated by Django 3.1.1 on 2020-10-06 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20201006_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users'),
        ),
    ]
