# Generated by Django 3.1.1 on 2020-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20201006_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='amount',
            field=models.FloatField(max_length=1000),
        ),
    ]
