# Generated by Django 3.1.1 on 2020-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20201006_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='amount',
            field=models.FloatField(),
        ),
    ]
